using System;

namespace _22_04_2026__TASKS_C_
{
    internal class IPLmatch
    {
        static void Main(string[] args)
        {
            int team1Runs = 0;
            int team2Runs = 0;
            int team1wickets = 0;
            int team2weickets = 0;

            int rows = 2;
            int cols = 6;

            Random rdm = new Random();
            int[,] team1Score = new int[2, 6];
            int[,] team2Score = new int[2, 6];

            Console.WriteLine("team2 scores will be autogenerated : ");

            bool exitLoops = false;
            for (int i = 0; i < rows; i++)
            {
                for (int j = 0; j < cols; j++)
                {
                    int run = rdm.Next(0, 7);

                    if (run > 0)
                    {
                        team2Score[i, j] = run;
                        team2Runs += run;
                    }
                    else
                    {
                        team2weickets++;
                        if (team2weickets == 10)
                        {
                            exitLoops = true;
                            break;
                        }
                    }
                }

                if (exitLoops)
                    break;
            }

            Console.WriteLine("you are team1 playing batting : ");
            Console.WriteLine("now enter the score one by one : ");

            for (int i = 0; i < rows; i++)
            {
                for (int j = 0; j < cols; j++)
                {
                    Console.WriteLine($"enter score for {i} over {j} ball : ");
                    int run = Convert.ToInt32(Console.ReadLine());

                    if (run > 0)
                    {
                        team1Score[i, j] = run;
                        team1Runs += run;

                        // Team 1 wins while chasing
                        if (team1Runs > team2Runs)
                        {
                            int wicketsLeft = 10 - team1wickets;
                            Console.WriteLine(
                                $"Team 1 wins by {wicketsLeft} wickets"
                            );
                            return;
                        }
                    }
                    else
                    {
                        team1wickets++;

                        //  Team 1 all out before target
                        if (team1wickets == 10 && team1Runs <= team2Runs)
                        {
                            int runsMargin = team2Runs - team1Runs;
                            Console.WriteLine(
                                $"Team 2 wins by {runsMargin} runs"
                            );
                            return;
                        }
                    }
                }
            }

            Console.WriteLine("team 2 runs are : " + team2Runs);
            Console.WriteLine("team 2 wickets are : " + team2weickets);
            Console.WriteLine("team 1 runs are : " + team1Runs);
            Console.WriteLine("team 1 wickets are : " + team1wickets);

            // final result after full match
            if (team1Runs > team2Runs)
            {
                int wicketsLeft = 10 - team1wickets;
                Console.WriteLine(
                    $"Team 1 wins by {wicketsLeft} wickets"
                );
            }
            else if (team2Runs > team1Runs)
            {
                int runsMargin = team2Runs - team1Runs;
                Console.WriteLine(
                    $"Team 2 wins by {runsMargin} runs"
                );
            }
            else
            {
                Console.WriteLine("Match Draw");
            }
        }
    }
}
